### ISSUE TITLE
Make merkle tree balanced

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/ceramic-anchor-service#138]
[Our current implementation](https://github.com/ceramicnetwork/ceramic-anchor-service/blob/4615c814ed98bb17cba8902480d8f22bde5397a1/src/merkle/merkle-tree.ts#L46-L65) of building the merkle tree creates a left-leaning tree.  This is because it merges nodes into pairs by iterating left-to-right over the nodes at each level.  Instead, we should be dividing the nodes at each level into two group at the middle index and then recursively building each half of the tree and merging those halves.  For a simple example of the tree we'll build with our current implementation vs what we should be producing, see this image: https://docs.google.com/drawings/d/1kt-b2OwG37_HyfjOh3oiUKUyL-3ink7y92aV5Z-kKzo/edit?usp=sharing

**Comment by oed** [comment]
Thanks for catching this. Let's try to get to it when we implement the new anchor structure!
