### ISSUE TITLE
Check for ethereum tx receipt status

### ISSUE THREAD

**Issue by valmack** [ceramicnetwork/ceramic-anchor-service#209]
A transaction could fail after it is sent to the network. We should check the status of sent transactions when we receive the receipt, log success/failure, and capture this status in the Transaction object.

See https://github.com/ceramicnetwork/ceramic-anchor-service/blob/develop/src/services/blockchain/ethereum/ethereum-blockchain-service.ts#L113-L117 where this should be done.

**Comment by valmack** [comment]
@simonovic86 do we want to retry in the case that a transaction comes back with a failure status?

**Comment by simonovic86** [comment]
@valmack yeah, definitely 👍
