### ISSUE TITLE
Env vars not being read

### ISSUE THREAD

**Issue by valmack** [ceramicnetwork/ceramic-anchor-service#249]
Add a .env file doesn't allow those variables to be read into config.

This was made evident from the service trying to continually connect to ganache which is the default network.

**Comment by valmack** [comment]
> For example if the NODE_ENV variable is set to production the env/production.json configuration will be merged with default.json and override default values with its own.
https://www.npmjs.com/package/node-config-ts

**Comment by stbrody** [comment]
I don't quite follow, is there a bug in the CAS that needs to be fixed there?  Or is this just some behavior we have to work around in how we deploy it?

**Comment by valmack** [comment]
Not an actual bug. Closing this
