### ISSUE TITLE
Ceramic loadDocument invalid json response

### ISSUE THREAD

**Issue by valmack** [ceramicnetwork/ceramic-anchor-service#262]
Seeing This error when attempting to get anchor requests on startup

```
FetchError: invalid json response body at https://ceramic-clay-internal.3boxlabs.com/api/v0/documents/k6zn3rc3iwgu6m1cqttm2kk7tlwmohtttm44rwc9mranxdhzizvzxvcwr6db721dghj9eh8nrec2r52kwq0xlsvr57ldzytaxie2viflw37rv9tkjemtls8 reason: Unexpected token < in JSON at position 0
```

This is potentially an error that is occurring in Ceramic and being propagated here

<img width="1135" alt="Screen Shot 2021-01-12 at 2 39 52 PM" src="https://user-images.githubusercontent.com/8445610/104364275-6644e580-54e4-11eb-9d2d-afff9be3ef43.png">

**Comment by valmack** [comment]
This seems to be the same issue as we see here https://github.com/3box/ceramic-infra/issues/200

**Comment by valmack** [comment]
Still seeing this because we are getting the response back from the load balancer, not the ceramic api.

**Comment by oed** [comment]
Is this still something that needs to be addressed at some point @valmack ? Or is it closed now that we have better connectivity?

**Comment by valmack** [comment]
@oed since this was related to lb timeouts I think we are good to close.
