### ISSUE TITLE
Validate that signed records are valid

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/ceramic-anchor-service#27]
Right now we replace signed records with new signed records that update the same document. This could be a problem since someone could send an invalid signed update to the anchor service that updates a document which it's not allowed to. This would cause the anchor service to remove the valid record and instead anchor the invalid one.

We should validate that the signed record being requested to be anchored is valid for the given document.

Note that this requires the anchor service to run a ceramic node in order to sync and validate the state of any given document.

**Comment by stbrody** [comment]
CAS now relies on Ceramic to validate any commit it tries to anchor
