### ISSUE TITLE
Add timeout when loading documents from Ceramic

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/ceramic-anchor-service#325]

**Comment by valmack** [comment]
Addressed by #327

**Comment by valmack** [comment]
What we really need is a timeout passed into the Ceramic api or a way to abort the actual request. Otherwise we just end up making multiple simultaneous requests to Ceramic which is likely to lead to failures for documents that would have otherwise been loaded

**Comment by stbrody** [comment]
Yeah, ideally the request would time out ceramic-side as well.  But as we discussed offline, I don't think there's anything that causes one failed request to snowball into multiple requests, so I think this is fine for now.
