### ISSUE TITLE
Investigate alternative gas estimation libraries

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/ceramic-anchor-service#404]

**Comment by stbrody** [comment]
It looks like what ethers, web3, and metamask (in some cases) all do is just a simple wrapper around the ethereum [JSON RPC](https://eth.wiki/json-rpc/API) `eth-gasPrice` method.

It does seem like Metamask in some cases (not clear to me when, the code is big and complex) will instead make a [call to the metaswap API](https://github.com/MetaMask/metamask-extension/blob/09d81ac5f2c94d7730d2e981b4f05734858030bf/ui/ducks/gas/gas.duck.js#L100) which [returns 3 values](https://github.com/MetaMask/metamask-extension/blob/09d81ac5f2c94d7730d2e981b4f05734858030bf/ui/ducks/gas/gas.duck.js#L143-L146): `SafeGasPrice`, `ProposeGasPrice`, and `FastGasPrice`.

I can't find any documentation on that metaswap API, but the basic form of the API looks very straightforward, so we could probably give it a shot if we wanted. Only problem is I'm not sure if there's a version for Ropsten or any other Eth testnets, so then we'd wind up with a different gas estimation approach on mainnet from testnet.

**Comment by oed** [comment]
Ah, yeah using the JSON-RPC is probably not optimal. 
I assume that the metaswap API is not publicly available. Maybe we can get access? cc @dazuck 

There is also this: https://etherscan.io/apis#gastracker

**Comment by stbrody** [comment]
This ticket was for investigating the landscape of gas estimation.  That part is done.  For now our current approach to gas estimation + retries seems to be working. Closing this ticket
