### ISSUE TITLE
Do database schema migration on CAS database to add 'pinned' field to Request table

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/ceramic-anchor-service#488]
- [x] dev
- [x] tnet
- [x] prod

**Comment by stbrody** [comment]
Okay, I really wanted to create a process for database schema migrations that could be managed in code and done programmatically, so we'd have a process that's easier to follow once we have partners running their own CAS nodes.

But for now I have failed and I don't think it makes sense to spend more time on this at this point.  So in the interest of unblocking this work and keeping moving, I'm going to recommend that we just do the migration manually this time.  That means I'm handing off this ticket to the platform team to execute @v-stickykeys.

We need to add a boolean field, `pinned` to the request table in the CAS database.  All existing rows in the database should default to having the value `false` set for this column.  As part of this, we should also make sure to update the `TYPEORM_SYNCHRONIZE` environment variable to `false`, or else typeorm will try to forcibly sync the database schema to the contents of the model definitions, potentially losing data in the process.

Please let me know if you have any questions or want to pair up on this @v-stickykeys

**Comment by v-stickykeys** [comment]
```
ALTER TABLE public.request ADD COLUMN pinned BOOLEAN;
UPDATE public.request SET pinned = false;
```

**Comment by stbrody** [comment]
As part of this we should set the `TYPEORM_SYNCRHONIZE` environment variable on all our CAS deployments to `false`

**Comment by v-stickykeys** [comment]
Done on dev ![image.png](https://images.zenhubusercontent.com/5e4518ac503aa45865db188a/d2522255-1697-4a10-8a00-3978881cb6c7)

**Comment by v-stickykeys** [comment]
Checked CAS clay and mainnet and they are both set correctly
![image.png](https://images.zenhubusercontent.com/5e4518ac503aa45865db188a/1e555f4f-425a-44bb-bca3-67c1a5d12dab)

**Comment by v-stickykeys** [comment]
![image.png](https://images.zenhubusercontent.com/5e4518ac503aa45865db188a/631118f0-e96b-4cf1-b088-ab5697a1b0cc)
