### ISSUE TITLE
Update deps: js-ipfs and friends

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/ceramic-anchor-service#511]
We should update the following packages:
- `dids`
- `multiformats`
- `dag-jose`
- `ipfs-http-client`
- `ipld-dag-cbor` replace with: `@ipld/dag-cbor`

**Comment by ukstv** [comment]
Hey, @stephhuynh18, for `ipfs.dag.put` with `dag-jose` (see Dispatcher code) API changed to `{ storeCodec: 'dag-jose', hashAlg: 'sha2-256' }`.
