### ISSUE TITLE
Load stream and filter out request CIDs already included in the log before sending multiquery

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/ceramic-anchor-service#530]
When loading streams in the CAS we use a single large multiquery for every commit that has a pending anchor request on the stream.  For streams that were updated many times in this batch we wind up with a very large multiquery containing multiple commitids for the stream.  This can take a long time to run on Ceramic and slow things down and lead to spurious timeouts.  We could improve this by first issuing a regular loadStream request for the base stream, and then filter out any commitIDs that show up in the loaded log.  Then we can do a second request as a multiquery including the commitIDs for any commits that we have requests for but didn't show up in the log.

**Comment by oed** [comment]
duplicate of completed ticket, closing
