### ISSUE TITLE
Encode StreamID of streams being anchored in anchor merkle tree

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/ceramic-anchor-service#565]
See https://github.com/ceramicnetwork/js-ceramic/issues/1967 for explanation of the problem we are trying to solve

**Comment by stbrody** [comment]
This will likely change the structure of the merkle tree and thus require changes to js-ceramic as well to support verifying anchors with the new format.

**Comment by stbrody** [comment]
Currently, the leaf nodes of the merkle tree are just an array of two CIDs of SignedCommits that were anchored in this batch:

`[<cid1>, <cid2>]`

Proposed new format:

`[{ cid: <cid1>, streamID: <streamID string 1> }, { cid: <cid2>, streamID: <streamID string 2> }]`

Existing Ceramic nodes won't be able to verify anchors if the merkle tree uses this new format, so we should update Ceramic first to support the new format and have at least an RC out with that support before making the change to the CAS to use the new format.

**Comment by oed** [comment]
I think a better, simpler, and non-breaking change would be: https://github.com/ceramicnetwork/js-ceramic/issues/1967#issuecomment-1002748760

**Comment by oed** [comment]
Alternatively instead of the propsed,

```ts
[{ cid: <cid1>, streamID: <streamID string 1> }, { cid: <cid2>, streamID: <streamID string 2> }]
```

we could do,

```ts
[{ commitId: <commitId-1-bytes> }, { commitId: <commitId-2-bytes> }]
```

**Comment by oed** [comment]
Another alternative if we end up implementing https://github.com/ceramicnetwork/js-ceramic/issues/1968 would be to encode a streamId if it's the genesis commit, otherwise just the CID of the commit:

```js
[ <cid1>, <streamId2> ]
```

**Comment by stbrody** [comment]
Of the two proposals you just suggested, I like the former that always uses CommitIDs better.  A small amount of data duplication is worth it for consistency and clarity IMO.

I still prefer my proposal though to use an object for the future extensibility.

**Comment by stbrody** [comment]
Another idea from @oed via discord conversation:

We leave the first two entries of the merkle tree leaf nodes as-is: the two CIDs of the anchored commits.  But we add a third element to the array that is an object that can contain additional metadata about the commits.  The keys would be the index of the anchored CID in the array (so always either '0' or '1'), and the value would be an object that could contain whatever additional metadata is needed.  In our case this would be the StreamID of the updated stream.

For example:

`[ <cid0>, <cid1>, { '0': <streamid0>, '1': <streamid1>} ]`

**Comment by oed** [comment]
Hm, I think we can do better:
```ts
interface Entry {
  type: Uint8Array // the stream type varint
}

interface Metadata {
  [index: string]: Entry
}

type leaf = [CID, CID, Metadata]
```

StreamType varint: https://github.com/ceramicnetwork/CIP/blob/main/CIPs/CIP-59/CIP-59.md#streamid

In addition to the above suggestion, if we end up implementing https://github.com/ceramicnetwork/js-ceramic/issues/1968 we don't need to include the metadata entry for commits which have a streamId in their `id` property.

**Comment by oed** [comment]
Another alternative could be to not include this information in the leaf node. Consider the current batch anchor data structure:

![image](https://user-images.githubusercontent.com/3909429/147700674-43d488bb-48bc-4784-b71e-5b54eb2fd3dd.png)

We could include extra metadata in the *TreeMetadata* directly. Could look something like this:

```
type MerkleNode [Link]

type BloomMetadata struct {
  type String
  data {String:any}
}

type StreamTypeList [Bytes]

type TreeMetadata struct {
  numEntries Int
  bloomFilter BloomMetadata
  streamTypeList StreamTypeList
}
```
In the above example we simply have a list with streamType varints stored in the *TreeMetaData*. This list should be ordered in the same way as the streams in the leafs.
