### ISSUE TITLE
A `Segmentation fault` has occurred

### ISSUE THREAD

**Issue by lyd0** [ceramicnetwork/ceramic-anchor-service#653]
# Description

Hello, I am deploying a local network ceramic, the documentation says I need to deploy a cas service
Then I cloned this project, and run ` cd ./config && docker-compose up -d` , the following error occurred, what should I do to deploy a cas service? Thank you!
<img width="413" alt="image" src="https://user-images.githubusercontent.com/29918052/173178589-3d4c9f1c-df81-425e-8111-cb942b23b12c.png">

**Comment by lyd0** [comment]
@stbrody hello, Can I deploy a local node without using the cas service?

**Comment by oed** [comment]
If you want to run Ceramic locally for testing you can spin it up on the `inmemory` network which will use a mock CAS:

```
ceramic daemon --network inmemory
```

```
--network <name>                  Name of the ceramic network to connect to. One of: "mainnet",
                                    "testnet-clay", "dev-unstable", "local", or "inmemory". Defaults to
                                    "testnet-clay"
```

**Comment by smrz2001** [comment]
@lyd0, are you seeing this failure consistently? I'm able to consistently build the image via `docker-compose up` during my testing.

What operating system are you using?
