### ISSUE TITLE
Validate that document updates (Ceramic side)

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/ceramic-anchor-service#96]
Check that update is valid before anchoring it. To do this, we will need to have a Ceramic node running somewhere.

Possibly need to add a check valid rest api.

**Comment by simonovic86** [comment]
The task description is no longer valid. We decided to add `nonce`s to records `header` so the CAS would know how to decide what anchor record is valid. This task can be split into:

- [ ] Adapt mock anchor service and test various anchoring edge cases
- [ ] Ceramic side (client)
- [ ] CAS (server)
- [ ] Consecutive update records squashing (optimization)
